#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KohrtaTimer.Resource", IsApplication=true)]

namespace KohrtaTimer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int backButton = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int decreaseRoundsButton = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int decreaseTimeOffButton = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int decreaseTimeOnButton = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int increaseRoundsButton = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int increaseTimeOffButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int increaseTimeOnButton = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int mainTextView = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int roundsElapsedTextView = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int roundsTextView = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int startButton = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int startTimerButton = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int stepsCounted = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int stopTimerButton = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int timeElapsedTextView = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int timeOffEditText = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int timeOnEditText = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int title1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int title2 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int title3 = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int totalTimeTextView = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int SettingsLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int TimerLayout = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int Dune = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GOGOGO = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int STOP = 2130903042;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int total_time = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
